### ISSUE TITLE
Django 1.8 compatibility

### ISSUE THREAD

**Issue by lorinkoz** [django-tastypie/django-tastypie#1291] opened 2015-04-21 15:05 UTC
Running Django 1.8 and Django-Tastypie 0.12.1 on Windows, Python 2.7, running `manage.py check` fails with this error:
```
  File "C:\Python27\lib\site-packages\tastypie\resources.py", line 2210, in Base
ModelResource
    @transaction.commit_on_success()
AttributeError: 'module' object has no attribute 'commit_on_success'
```
The decorator was removed in this version of Django, so says Django documentation

> These features have reached the end of their deprecation cycle and so have been removed in Django 1.8 (please see the deprecation timeline for more details):
> ...
> * the decorators and context managers `autocommit`, `commit_on_success`, and `commit_manually`, defined in django.db.transaction
> ...

**Comment by georgedorn** [comment] 2015-04-21 17:45
Duplicate of #1290, #1288, #1281, #1250.

The 1.8-compatible release is not yet on PyPI.  It is still being beta-tested.  Feel free to use master and report bugs to help us beta-test.

**Closed by georgedorn** 2015-04-21 17:45 UTC
