### ISSUE TITLE
Put / patch requests on non PK data

### ISSUE THREAD

**Issue by nicerworld** [django-tastypie/django-tastypie#1323] opened 2015-08-16 22:14 UTC
I am using detail_uri_field as follows to get rid of IDs out of data, I need business growth to be a secret. This works great on GET requests...

class Meta:
	detail_uri_name='uuid'
	def prepend_urls(self):
		return [
			url(r'^(?P<resource_name>%s)/(?P<uuid>[\w\.-]+)/$' % self._meta.resource_name, self.wrap_view('dispatch_detail'), name='api_dispatch_detail'),
		]

But on PATCH/ PUT I get a duplicate error, i.e, it's doing a create rather than update  It looks to me as though the uuid doesn't get used to get the object that needs updating, is this true? I am in the source but hoping someone can help me solve this the right way!
Thanks
Rich

**Comment by nicerworld** [comment] 2015-08-16 22:34
In addition, when I do a get request on  /api/v1/user/fb2fe716ca03413496a58cc8868c0fd5/?format=json

I get back data with no resource URI. I tried adding one matching above, I even tried adding an ID field to the JSON posted with the actual ID of the object to see if it would give me a clue, but it's still trying to create rather than update.

**Comment by SeanHayes** [comment] 2015-10-10 08:12
I think specifying Meta.detail_uri_name should be all you need to do. The regex in your prepend_urls doesn't look quite right.

Could you post your models and resources? If you're still having trouble I can put together a test case and try to fix the issue.

**Comment by SeanHayes** [comment] 2015-10-10 08:13
Note to self/devs: need more tests where detail_uri_name gets customized.

**Comment by burnhambp** [comment] 2015-10-16 13:51
Hi Sean,

I moved onto a different area of project but I am back to it now and could really use a fix! 

I can confirm this is definitely an issue. Doing a put request to the resource_uri returned on a resource is creating a new record. 

I think someone else had this issue as well (http://newscentral.exsees.com/item/47beeac8c38dde2a7bd948472a007f39-a9afeea5ae05fd8dbf1551104be330b4)

Here is my resource:

class BusinessAreaResource(ModelResource):
	class Meta:
		detail_uri_name='uuid'
		queryset = BusinessArea.objects.all()
		resource_name = 'business_area'
		always_return_data = True
		authentication = Authentication() 
		authorization = Authorization()
		excludes=['id', 'created']

	def override_urls(self):
		return [
			url(r'^(?P<resource_name>%s)/(?P<uuid>[\w\d_.-]+)/$' % self._meta.resource_name, self.wrap_view('dispatch_detail'), name='api_dispatch_detail'),
		]

Here is the model:

class BusinessArea(models.Model):
	uuid 		= models.UUIDField(default=uuid.uuid4)
	created		= models.DateTimeField(default=timezone.now)
	published 	= models.BooleanField(default=True)
	creator_id	= models.IntegerField()
	label		= models.CharField(max_length=100)	

I do a GET request, I get back a list of objects and their resource_url is correctly using the UUID field. I pick the first object, modify the label and then do a PUT request to its resource_url:

/api/v1/business_area/d64b165a-9ed5-41d5-8dbd-35214bf6e527

with the following data:

{"creator_id":40,"label":"modified label","published":true,"resource_uri":"/api/v1/business_area/d64b165a-9ed5-41d5-8dbd-35214bf6e527
/","uuid":"d64b165a-9ed5-41d5-8dbd-35214bf6e527"}

Instead of modifying the label, I get a new record with the same UUID. Normally I would get a duplicate key error but I am not yet enforcing unique on the UUID field. 

I noticed you created another request to check use of PK where detail_uri_name should be used. I hope you can help sooner rather than later. 

Thanks

Rich

**Comment by SeanHayes** [comment] 2015-10-18 07:10
I think declaring uuid as unique might help. This is likely a bug in tastypie though, since you did specify detail_uri_name like you should and I know 'pk' is hardcoded in a few places. 

I'll try to get this fixed Monday if not this weekend.

**Comment by nicerworld** [comment] 2015-10-18 13:52
Thanks Sean,

I find it hard to imagine why the code might decide how to handle a PUT
request based on whether UUID is unique but as it should be unique anyway,
no harm in setting it and seeing what happens! I'll report back a bit
later.


Thanks

Rich

On Sun, Oct 18, 2015 at 8:10 AM, Seán Hayes <notifications@github.com>
wrote:

> I think declaring uuid as unique might help. This is likely a bug in
> tastypie though, since you did specify detail_uri_name like you should and
> I know 'pk' is hardcoded in a few places.
>
> I'll try to get this fixed Monday if not this weekend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/issues/1323#issuecomment-148986220>
> .
>



-- 



[image: Inline image 1]

Richard Jones

Mobile: +44 7984 203090

Skype: richardjones2102

Email:  richard.jones@nicerworld.com





DISCLAIMER: This message is proprietary to NicerWorld and is intended
solely for the use of the individual to whom it is addressed. It may
contain privileged or confidential information and should not be circulated
or used for any purpose other than for what it is intended. If you have
received this message in error, please notify the originator immediately.
If you are not the intended recipient, you are notified that you are
strictly prohibited from using, copying, altering, or disclosing the
contents of this message. NicerWorld accepts no responsibility for loss or
damage arising from the use of the information transmitted by this email
including damage from virus."

**Comment by SeanHayes** [comment] 2015-10-20 06:19
I wasn't able to reproduce the bug. In 1 or 2 places Tastypie looks up objects using 'pk' or any unique field, but in put_detail it correctly uses detail_uri_name.

My guess is it might actually be related to the UUIDField. Tastypie is probably using a CharField to represent it, which may not be hydrating the value correctly if UUIDField only works with a UUID object.

**Comment by SeanHayes** [comment] 2015-10-20 07:14
OK, I was able to reproduce it, and it's not exactly limited to UUIDs. Any time you use a detail_uri_name with a default value this will happen, because Tastypie creates a new object and assigns it to bundle.obj before trying to lookup via detail_uri_name.

**Comment by burnhambp** [comment] 2015-10-20 08:46
Thanks Sean, it's great you got to reproduce it. So do I need to remove the default value for UUID and override methods to set it on object creates?

**Comment by SeanHayes** [comment] 2015-10-20 19:18
A workaround would be to set the default value manually in the save() method on your model. However, the Django docs actually recommend using a default value, and this bug is caused by the unique way Tastypie does things, so I think we'll need to fix it in Tastypie.

I opened a PR, but want to come up with a better solution. I think I’ll have one tonight merged into master.

**Comment by nicerworld** [comment] 2015-10-20 20:46
Thanks Sean,

I appreciate your totally thorough approach.

Regards,

Rich

On Tue, Oct 20, 2015 at 8:19 PM, Seán Hayes <notifications@github.com>
wrote:

> A workaround would be to set the default value manually in the save()
> method on your model. However, the Django docs actually recommend using a
> default value, and this bug is caused by the unique way Tastypie does
> things, so I think we'll need to fix it in Tastypie.
>
> I opened a PR, but want to come up with a better solution. I think I’ll
> have one tonight merged into master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/issues/1323#issuecomment-149673812>
> .
>



-- 



[image: Inline image 1]

Richard Jones

Mobile: +44 7984 203090

Skype: richardjones2102

Email:  richard.jones@nicerworld.com





DISCLAIMER: This message is proprietary to NicerWorld and is intended
solely for the use of the individual to whom it is addressed. It may
contain privileged or confidential information and should not be circulated
or used for any purpose other than for what it is intended. If you have
received this message in error, please notify the originator immediately.
If you are not the intended recipient, you are notified that you are
strictly prohibited from using, copying, altering, or disclosing the
contents of this message. NicerWorld accepts no responsibility for loss or
damage arising from the use of the information transmitted by this email
including damage from virus."

**Comment by SeanHayes** [comment] 2015-10-21 05:57
Try it now with the latest master branch.

**Closed by SeanHayes** 2015-10-21 05:57 UTC
Labels: bug, immediate
