### ISSUE TITLE
[URGENT] Is tastypie 0.13.3 supporting django 1.11?

### ISSUE THREAD

**Issue by sp1rs** [django-tastypie/django-tastypie#1513] opened 2017-06-29 07:42 UTC
Hi, Need to now if tastypie latest version is supporting Django 1.11?

**Comment by georgedorn** [comment] 2017-06-29 08:43
Duplicate of #1490.

Django 1.11 support is in progress.  The master branch should be compatible, but there are some warnings to fix before a new version is released.

**Closed by georgedorn** 2017-06-29 08:43 UTC
