### ISSUE TITLE
'module' object has no attribute 'commit_on_success'

### ISSUE THREAD

**Issue by alikoubeissi** [django-tastypie/django-tastypie#1290] opened 2015-04-14 21:39 UTC
Hey guys,

I just instalked tastypie v0.12.1 on Django 1.8 and Python 2.7 and I'm getting the following exception: 'module' object has no attribute 'commit_on_success'.

Exception Location:	/home/vagrant/project/local/lib/python2.7/site-packages/tastypie/resources.py in BaseModelResource, line 2210

Any ideas? I'm only doing the examples found in the quickstart section of the tutorial.

**Comment by georgedorn** [comment] 2015-04-14 21:45
The code supporting Django 1.8 has not been released to PyPI yet.  It has, however, been merged to master, so for now you can install from there instead (e.g. pip install -e https://github.com/django-tastypie/django-tastypie#egg=TastyPie)

Closing as duplicate of #1250, #1281 and especially #1288.

**Closed by georgedorn** 2015-04-14 21:45 UTC

**Comment by Eagllus** [comment] 2015-04-15 05:54
Related to this point, is there a release date for the new version compatible with Django 1.8?

**Comment by mhkeller** [comment] 2015-04-22 15:39
The pip command that worked for me needed `git+` before the url

````
pip install -e git+https://github.com/django-tastypie/django-tastypie#egg=TastyPie
````

**Comment by geghamjivanyan** [comment] 2015-06-05 20:43
Hi All
just install tastypie by pip install -e git+https://github.com/django-tastypie/django-tastypie#egg=TastyPie
and now I.m getting the following error
type object 'ModelDeclarativeMetaclass' has no attribute 'Meta'

Any idea?
