### ISSUE TITLE
Tastypie does not work with Django 1.8

### ISSUE THREAD

**Issue by pavelkuchin** [django-tastypie/django-tastypie#1288] opened 2015-04-06 16:33 UTC
Django 1.8 has been released recently but we can't upgrade it because of Tastypie issue.
```
Traceback (most recent call last):
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/tests/test_api.py", line 290, in test_without_invitations
    self.auth(True)
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/tests/test_api.py", line 65, in auth
    data=auth_data
  File "/usr/local/lib/python2.7/dist-packages/tastypie/test.py", line 104, in post
    return self.client.post(uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 512, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 313, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 448, in request
    response = self.handler(environ)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 122, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/src/rw_tracker/tracktrains/tracktrains/urls.py", line 6, in <module>
    from profiles.api import TrackTrainsUserResource
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/api.py", line 8, in <module>
    from tastypie.resources import ModelResource
  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 1740, in <module>
    class BaseModelResource(Resource):
  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 2210, in BaseModelResource
    @transaction.commit_on_success()
AttributeError: 'module' object has no attribute 'commit_on_success'
Traceback (most recent call last):
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/tests/test_api.py", line 290, in test_without_invitations
    self.auth(True)
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/tests/test_api.py", line 65, in auth
    data=auth_data
  File "/usr/local/lib/python2.7/dist-packages/tastypie/test.py", line 104, in post
    return self.client.post(uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 512, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 313, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 448, in request
    response = self.handler(environ)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 122, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/src/rw_tracker/tracktrains/tracktrains/urls.py", line 6, in <module>
    from profiles.api import TrackTrainsUserResource
  File "/home/vagrant/src/rw_tracker/tracktrains/profiles/api.py", line 8, in <module>
    from tastypie.resources import ModelResource
  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 1740, in <module>
    class BaseModelResource(Resource):
  File "/usr/local/lib/python2.7/dist-packages/tastypie/resources.py", line 2210, in BaseModelResource
    @transaction.commit_on_success()
AttributeError: 'module' object has no attribute 'commit_on_success'
```

**Comment by georgedorn** [comment] 2015-04-07 01:44
Duplicate of #1263, #1274, #1257, #1147.

**Closed by georgedorn** 2015-04-07 01:44 UTC
