### ISSUE TITLE
django 1.8 version

### ISSUE THREAD

**Issue by kalvish21** [django-tastypie/django-tastypie#1293] opened 2015-04-30 15:07 UTC
I see that there're are several commits for django 1.8 release compatibility.

Any idea when this will be pushed to pip?

**Comment by dhui** [comment] 2015-05-05 00:38
+1 for a new django-tastypie version in PyPi

**Comment by pkuchin** [comment] 2015-05-05 07:37
+1

**Comment by pavelkuchin** [comment] 2015-05-05 07:40
+1

**Comment by hassek** [comment] 2015-05-05 12:58
+1, Any ETA for it?

**Comment by georgedorn** [comment] 2015-05-05 17:15
Unfortunately I can't update PyPI myself, as far as I know.  However, if
you are waiting for the new version, you can help us out a lot by
installing from master and trying it out on some staging or test servers
and filing reports on any bugs you find.  There was a refactor of a large
section of code pertaining to related resources (foreign keys, one-to-one
and many-to-many) that could use some more real-world testing.

Installing from master:
pip install -e git+
https://github.com/django-tastypie/django-tastypie.git#egg=TastyPie

**Comment by kalvish21** [comment] 2015-05-05 17:25
Running it already on my development and staging servers.

pip install -e git+https://github.com/django-tastypie/django-tastypie.git#egg=TastyPie

**Comment by pavelkuchin** [comment] 2015-05-05 18:58
Master is on my dev server, all unit tests have been passed successfully.

**Comment by hassek** [comment] 2015-05-06 12:30
I have our staging system running it on the master version of tastypie but we use our own Resource system adapted to mongodb so all this related resources won't apply. Anything else seems to be working pretty gewd.

**Comment by gorillamania** [comment] 2015-05-13 22:20
Have been running master in production for a few days, no problems. +1 for pip update.

**Comment by bartmika** [comment] 2015-05-25 22:57
+1

**Comment by AyumuKasuga** [comment] 2015-05-26 08:41
+1

**Comment by xmdy** [comment] 2015-05-26 08:41
+1

**Comment by grey0ne** [comment] 2015-05-26 08:42
Desperately need this

**Comment by Barnalite** [comment] 2015-05-26 14:34
+1

**Comment by Eagllus** [comment] 2015-05-27 06:29
+1

**Comment by Tritlo** [comment] 2015-05-28 01:38
+1

**Comment by dyve** [comment] 2015-06-03 06:17
+1 for publish to PyPI

**Comment by buzzijavier** [comment] 2015-06-03 12:28
+1

**Comment by ssjunior** [comment] 2015-06-05 18:06
Hi @georgedorn @toastdriven,

Tastypie is a great project and the job done until now is certainly amazing. But, just to understand, what is the real status of Tastypie? I can see more 200 PR from the community but most of them is in the queue for approval. 

Django 1.8 was in pipeline for several months and now Django 1.9 is in the near future. Since Tastypie moves slowly compared to Django, I think that should be good to everyone to see what can be expected from Tastypie Dev Team so we can adjust our expectations accordingly.  Maybe open space to new contributors? Maybe this way we can see faster updates in the master branch.

I ask because we are doing a lot of work based on Tastypie and should be great for us to understand what we can expect for the next months.

Thanks for the great job until now and please keep doing it. :+1: 

Kind regards

**Comment by aisayko** [comment] 2015-06-09 11:31
+1 for @ssjunior comment

**Comment by gulfpearl** [comment] 2015-06-17 19:15
+1 @ssjunior comment ...

**Comment by hhio618** [comment] 2015-06-17 20:01
+1 @ssjunior  I'm using master in production no problem so far.
please keep going great works devs :)

**Comment by amitnabarro** [comment] 2015-06-21 10:16
+1 @ssjunior comment ...

**Comment by pavelkuchin** [comment] 2015-06-22 14:19
+1 for @ssjunior comment

**Comment by scenting** [comment] 2015-06-30 12:21
:+1:  for @ssjunior comment

**Comment by Galaf** [comment] 2015-07-06 07:45
+1 @ssjunior 
+1 pip update

**Comment by mrgaolei** [comment] 2015-07-08 04:12
+1

**Comment by doctorwidget** [comment] 2015-07-08 15:55
+1

**Comment by georgedorn** [comment] 2015-07-08 19:28
I've created a tag for version 0.12.2 (https://github.com/django-tastypie/django-tastypie/tree/v0.12.2) with release notes and version number bumps, but don't have the authorization to update PyPI myself.  I believe @toastdriven is the only one that can publish to PyPI.

**Comment by borfast** [comment] 2015-07-08 23:01
@toastdriven, could you take care of the Pypi update, please? It's currently the last thing blocking us from upgrading to Django 1.8. Thanks! :)

**Comment by Galaf** [comment] 2015-07-09 01:42
+1 @toastdriven Could you update Pypi, please?

**Comment by scenting** [comment] 2015-07-09 10:14
Thanks @georgedorn !

v0.12.2 fails for Django 1.8 as "@transaction.commit_on_success()" is being used on resources.py:

https://github.com/django-tastypie/django-tastypie/blob/v0.12.2/tastypie/resources.py#L2210

**Comment by Lobosque** [comment] 2015-07-10 18:13
I have the same problem as @georgedorn

**Comment by Lobosque** [comment] 2015-07-10 18:32
The problem is that commit_on_success was deprecated in django 1.6 and removed in 1.8. Using atomic instead solves the problem. There are other issues though. Tastypie 0.12.2 is definitely not ready for 1.8. I will fork and commit my changes this weekend.
I wonder if there is any use in making pull requests, since there are 200+ pending?
@toastdriven We all appreciate your work so far with tastypie, but if you can't maintaing it anymore you have to let the community know so it can move on and find another maintainer for the project.

**Comment by ssjunior** [comment] 2015-07-10 19:01
@Lobosque @scenting @Galaf @borfast @georgedorn @pavelkuchin @kalvish21 @hassek 

Plan A
-----------------------------------
I dont understand why @toastdriven do not answer people or approve PR's. Maybe he is busy or having some kind of personal issues. Maybe this moment is complicated in his life.

@toastdriven thank you so much for your great work, but,  please,  PLEASE, to avoid Tastypie fade away, open the project and give administrator access to other people so we can help each other. Give access to @georgedorn or someone that you trust.


Plan B
-------------------------------------
Just in case we do not receive an answer, I forked Tastypie and hosted on https://github.com/Tastypie-Django/tastypie to prepare to push to Pypi as a new project. 

Everyone is invited to be administrator/developer of this new project so we can move forward and not depend from only a single person. Let's work together to publish a new version on Pypi.

**Comment by ssjunior** [comment] 2015-07-10 19:02
@Lobosque you are an administrator of Tastypie-Django. Can you please be so kind and publish your commits in this repo?

**Comment by Lobosque** [comment] 2015-07-10 20:02
@ssjunior the 0.12.2 tag does not have the latest fixes for django 1.8, but the master branch does. Use it instead and it should work just fine.

**Comment by borfast** [comment] 2015-07-10 20:03
Daniel (@toastdriven) has explained his absence in a blog post some time ago and mentioned he would be giving other people access to the Tastypie (and Haystack) repositories so that the project could continue: http://toastdriven.com/blog/2015/feb/02/haystack-tastypie-orgs/

He also mentioned in another post that Tastypie «[has almost always been a maintanence burden that I develop in isolation](http://toastdriven.com/blog/2014/may/23/state-tastypie/)». In fact, the call for help comes all the way back from 2013:
http://toastdriven.com/blog/2013/feb/05/committers-needed-tastypie-haystack/
http://toastdriven.com/blog/2013/may/04/new-committers-tastypie-haystack/

I'm not mentioning all this as a critique to Daniel; in fact I am kind of supporting him here, because I understand the position he is in relatively to this project, and the project that caused my situation wasn't nearly as popular as Tastypie or Haystack. Sometimes this kind of thing just becomes too much and what started as a little fun project, turns into a major headache.

Anyway, unfortunately it appears that all this was still not enough to guarantee the continued support and development of the project and thus we find ourselves in this current situation.

I'm not sure what Daniel will decide about this and I appreciate @ssjunior's proactivity to get a solution for the problem, but I would like to see this fork eventually being merged back into the main project and new maintainers assigned to it, so that people can continue to use it.

Daniel, what do you say? :)

**Comment by ssjunior** [comment] 2015-07-10 20:13
@borfast Perfect your comment! 

I think the best solution is to help @toastdriven and mantain Tastypie as it is. Let's see if we can have some light in this situation. Hopefully someone here could get access to admin and start helping him.

**Comment by georgedorn** [comment] 2015-07-11 05:07
I must have tagged 0.12.2 off a stale repo; I was in a rush and trying to
see if tagging would grant the ability to update PyPI.

Master is 1.8-compatible; I'll delete and re-create the tag.

There is also a Plan C that was not suggested:  we contact PyPI management
about transferring credentials to the larger team.  I know this has been
done in the past for other projects (too easily, if I recall correctly) but
I'm unclear on the details.

Plan C would allow continuation of the package name, reduce confusion among
users and keep the commit standards that @toastdriven originally wanted.

**Comment by Galaf** [comment] 2015-07-11 05:20
All in for Plan C. It would be the less confusing plan.

**Comment by ssjunior** [comment] 2015-07-11 05:23
Agree. Let's try Plan C.

@georgedorn: Can you try to contact Pypi team? Do you have admin rights of Tastypie repo? Can I do something to help you?

**Comment by dhui** [comment] 2015-07-11 06:09
+1 for Plan C

**Comment by hassek** [comment] 2015-07-11 17:46
+1 for Plan C, good to know that kind of support exists :)

**Comment by dyve** [comment] 2015-07-11 17:48
Plan C. And much thanks for all of @toastdriven's work. 




I think for new projects and refactoring I'll go with plan D: drf

**Comment by gulfpearl** [comment] 2015-07-11 18:20
+1 for plan C.

**Comment by borfast** [comment] 2015-07-11 18:41
I like plan C but only if it is done by someone with commit privileges to this (the original) repository, because that will have been someone Daniel (@toastdriven) nominated for the role.

Having someone else do it will be a bit disrespectful, in my opinion, because it will basically be a "hostile" takeover, despite being done with good intentions.

Is any of the commentators here someone with access to this repository?

**Comment by gingerlime** [comment] 2015-07-11 19:08
@borfast: @georgedorn is a member of the django-tastypie org, with commit access. I'm also one of the members although I've been very inactive / silent, but I helped in the past with a few security-related aspects. The only owner of the organization is @toastdriven. I think plan C makes sense, and FWIW, I'm also in favour of it - if this is the only alternative to keep the project alive and move things forward.

It would still be useful if @toastdriven hands over ownership to one or more members, so they can take control of the github organization, add more members in future and so on. I'm not sure if there's a plan-C-equivalent for Github ownership of organizations, but if Daniel is unable to respond in a reasonable timeframe, it might be worth checking with Github as well.

I think it's important that this isn't seen as some kind of a coup, because from what I see it really isn't one.

**Comment by ssjunior** [comment] 2015-07-11 19:08
@borfast How can this be a hostile takeover? We are all here willing to help and respecting what have been done until now. 

We are begging for an answer from @toastdriven since April. 

How long you think we should wait more to be respectfull?  We all are very grateful to Daniel, but, we need to find a solution or declare Tastyie DEAD and move on. 

So in my opinion someone that have admin privilege on repo should try one last time to get an answer from @toastdriven or we should go with Plan C o B.

**Comment by gulfpearl** [comment] 2015-07-11 19:09
You are completely wrong, this is not hostile or disrespectful to anyone,
if @toastdriven is missing in action, there is nothing anyone can do about
it and we have to move on. Some of us rely on Tastypie for our livelyhood,
not just as a hobby. This is one of the great things about source, you
don't have to rely on one party for the software.


On Sat, Jul 11, 2015 at 2:41 PM, Raúl Pedro Santos <notifications@github.com

**Comment by gingerlime** [comment] 2015-07-11 19:12
@acdha @benspaulding @issackelly @numan @SeanHayes - as fellow members of django-tastypie, I think you could really help add your weight to this discussion (sorry to trouble you, but it feels important to the future of the project)

**Comment by borfast** [comment] 2015-07-11 19:19
@ssjunior, @gulfpearl: I did put "hostile" in between commas, hoping it would be obvious that I didn't mean hostile in the usual way.

What I meant was that despite everything and anything, this is still Daniel's project - and please note that I, too, am being affected by this issue; I am not saying the problem isn't real or that we shouldn't do something about it.

I just think it's not very respectful to come here, grab something that isn't ours and make it ours without the approval of one of the repository admins, that's all. Ideally this would be Daniel himself but yes, unfortunately it's rather unlikely that it will happen, so the next best thing is for his approved committers to give the green light.

Again, I'm not against you guys, quite the contrary. I just think we should be more considerate, thoughtful, respectful... I guess we just see this detail a bit differently. Maybe it's my traditional martial arts background speaking :)

**Comment by ssjunior** [comment] 2015-07-11 19:44
@borfast We are in the same boat. :) 

We should never, ever, grab work from others and get credit for it. No one is doing that. Please remember this is an open source project and Forking is very common and natural. Forking and making it available to community is the nature of the game.  

The problem here is that many of us depends on Tastypie and we do not have an answer from the owner, that we are very thankfull to by the way. I think that no one wants to be disrespectful but just find a way out.

I saw this situation happen is several open source projects and this time is happening here.

Again, I agree with your comment and the easy solution would be have more than one owner, but, there is only one person that could do that and he.... is not answering for months...

Hopefully the community will find a way out, we will use Tastypie for years to come and we will always very gratefull to @toastdriven  for the work done until now. :)

**Comment by borfast** [comment] 2015-07-11 20:42
Well, forking is a completely different matter - we have been talking about appropriating Tastypie without any of the current maintainer's blessing. ;)

Forking an open source project (we're not just talking about making a copy of the repository on Github, right?) means starting a new project, under a new name and leadership. That's certainly also a possibility, and given the situation, it's probably a solution I would recommend - I usually don't, since it means dividing efforts instead of teaming up, and just creates more confusion.

In my case, I am interested in fixing Tastypie because I have a big project in hands that depends on it. If it were a new project, not so dependent on Tastypie yet, I would probably just migrate to Django REST Framework, which is actively developed and maintained and enjoys a much broader community.

That's not the case, though, so I need to get Tastypie working with Django 1.8, at least until I manage to migrate to DRF.

The way I see it, forking Tastypie and starting a new project would be justified if there were a need for it, if there were no other alternatives, or if they were bad ones. As in "hey, let's revive Tastypie so that we can finally have a good web service framework for Django" - we already do, so it seems like a waste of effort to me.

Personally, with DRF available, I don't feel the need for Tastypie to be kept alive. Of course others might, my needs are not the same as everyone else's. If it were up to me, I would probably maintain Tastypie on life support just long enough for people to migrate to DRF, instead of creating a new project that gives the impression that Tastypie will live on. That means creating a "fork" of this repository but not "fork" the project.

What I mean is, I would create a forked repository of Tastypie here on Github, where patches could be applied and problems worked on, but *not* make it a new full blown community project, a real fork, like a totally new Tastypie or something with a completely different name.

On the other hand, if enough people with enough time to spare really want to keep Tastypie going with new functionality and supporting newer Django versions, then a full-blown fork is in order. Fork this repository, give the fork a new name, spread the word, try to get people involved...

Another reason I usually recommend this is because when people talk about forking an OSS project, they are usually all fired up, not thinking things through, not thinking about the long term of the project. Being responsible for a popular OSS project is a big deal. Just as an example, look at what happened with Daniel and Tastypie. You obviously don't want to repeat the same mistakes so many others have made.

One final comment about the fork idea: I would only go for this after either hearing from some of the current project's maintainers, or after a week or two had passed from this conversation. Someone might still be willing to open up this repository to more people so that the original Tastypie can live on.

**Comment by hassek** [comment] 2015-07-11 21:03
I see a couple of maintainers and a lot of commenters here willing to help,
please, let's stop the discussion about been respectful or not which I
think is not adding anything to the table since we can all agree we are not
on the disrespect train here.

I think Tastypie is active enough to start talking about migrating to DRF,
is not an abandoned child yet and if we can contact @toastdriven to share
ownership of the pie we will keep moving and get us full with some fresh
pie!

**Comment by borfast** [comment] 2015-07-11 21:10
@hassek, I think you guys were misunderstanding me. I know everyone here has nothing but the best intentions but you do understand that even if you are a good person wanting to help, you can still be disrespectful even without meaning to, right?

The term "disrespectful" is probably a bit too strong for what I meant. Maybe a better way to say what I meant would have been to say that I think we should "show courtesy", or "be polite".

That said, I thought we were past all that already. :)

**Comment by hassek** [comment] 2015-07-11 21:12
@borfast no no dude! I totally get you! I just think we have to move on from that theme :+1:

**Comment by SeanHayes** [comment] 2015-07-11 23:54
I'm in favor of Plan C. Even I can't get a response from toastdriven and I'm one of the contributors. I don't want to see things get too fragmented though by having everyone move to an unofficial fork.

**Comment by borfast** [comment] 2015-07-12 00:18
@SeanHayes, that fragmentation is exactly one of the things I'd like us to prevent, hence me suggesting we wait to see if anyone would say something. And here you are :)

Could you get in touch with Pypi and see what can be done about this, please?

**Comment by acdha** [comment] 2015-07-12 01:27
@SeanHayes I still have access to the PyPI admin. What's your username there?

**Comment by issackelly** [comment] 2015-07-12 17:47
@georgedorn @SeanHayes same, I'm in Daniel's boat, in that I no longer use Tastypie, and feel no compulsion to participate. I can however get both of you Pypi access.

**Comment by borfast** [comment] 2015-07-12 17:51
@acdha, @issackelly, thanks for chiming in, guys :) :+1:

**Comment by dyve** [comment] 2015-07-12 17:52
Great to see community step up. Hope this works out.

**Comment by georgedorn** [comment] 2015-07-16 19:53
@acdha @issackelly Yeah, getting PyPI access would be great.  My username there is George.Dorn (I have no recollection of registering, but I'm sure there was some reason.)

**Comment by georgedorn** [comment] 2015-07-16 20:01
Also, re-tagged ﻿0.12.2 off the right branch:  https://github.com/django-tastypie/django-tastypie/tree/v0.12.2

Moral:  don't push to github before coffee.

**Comment by acdha** [comment] 2015-07-16 21:51
@georgedorn You should be able to publish to PyPI now

**Comment by georgedorn** [comment] 2015-07-16 22:51
0.12.2 is now available on PyPI.

**Closed by georgedorn** 2015-07-16 22:51 UTC

**Comment by ssjunior** [comment] 2015-07-16 22:52
Tks to all who worked to find a solution. :+1:

**Comment by borfast** [comment] 2015-07-16 23:01
Thank you very much, guys! :) :+1:

**Comment by hassek** [comment] 2015-07-16 23:23
Thanks guys! let's keep enhancing tastypie!

**Comment by scenting** [comment] 2015-07-17 06:16
Thanks @georgedorn and @acdha

**Comment by Galaf** [comment] 2015-07-17 06:18
Thanks!

2015-07-17 15:16 GMT+09:00 Miguel González <notifications@github.com>:

> Thanks @georgedorn <https://github.com/georgedorn> and @acdha
> <https://github.com/acdha>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-tastypie/django-tastypie/issues/1293#issuecomment-122187561>
> .
>



-- 
LABONNE Christophe
