### ISSUE TITLE
ImportError: cannot import name 'QUERY_TERMS' on Django 2.1

### ISSUE THREAD

**Issue by bastbnl** [django-tastypie/django-tastypie#1561] opened 2018-08-01 20:07 UTC
Hi,

I just updated to Django 2.1 from Django 2.0.7 using `django-tastypie==0.14.1` on python 3.5 and ran into this error:
```
...
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/brownpapersession/dev/brownpapersession/brownpapersession/urls.py", line 16, in <module>
    from tastypie.api import Api, NamespacedApi
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/tastypie/api.py", line 11, in <module>
    from tastypie.resources import Resource
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/tastypie/resources.py", line 32, in <module>
    from django.db.models.sql.constants import QUERY_TERMS
ImportError: cannot import name 'QUERY_TERMS'

```

I'll see if I can find more information on `QUERY_TERMS`

**Comment by lhopkins** [comment] 2018-08-02 15:48
Looks like `QUERY_TERMS` [is removed](https://github.com/django/django/blob/a656a681272f8f3734b6eb38e9a88aa0d91806f1/docs/releases/2.1.txt#L396).

**Comment by georgedorn** [comment] 2018-08-06 15:37
This is turning into a fairly difficult problem to solve; tastypie was relying heavily on `QUERY_TERMS` to quickly pre-validate filters.  There doesn't appear to be a graceful way to regenerate that set of operators without overhauling `ModelResource.build_filters`.  This is long overdue, anyway; validating against a constant list of operators made it impossible to add more operators without monkey-patching, and the global list of operators meant it would allow nonsensical operations through for fields that make no sense, like a case-insensitive filter on an integer field.

The path forward is probably rebuilding `build_filters` to retrieve the Django field and use the new lookups api to validate the operation.

**Comment by georgedorn** [comment] 2018-08-13 14:48
This was fixed in #1564 and merged into the `django-2.1` branch.  That branch isn't ready for release due to other test failures (see #1562), but I've confirmed that the remaining test failures are unrelated to `QUERY_TERMS` so this issue can be closed.

**Comment by georgedorn** [comment] 2018-08-14 03:00
To avoid further confusion, I'll leave this issue open until the rest of 2.1 support is implemented and merged to master.

**Comment by georgedorn** [comment] 2018-08-28 15:10
The test suite is now passing under Django 2.1.  I'll release to PyPI on 9/3 if no major bugs are found before then.

This will also drop support for Django 1.8, which was EOL'd back in April.

**Comment by georgedorn** [comment] 2018-09-04 15:02
Released today.

**Closed by georgedorn** 2018-09-04 15:02 UTC
Labels: django-update, ready for release

**Comment by bastbnl** [comment] 2018-09-04 19:50
Appears to be working fine, @georgedorn Thanks!
