### ISSUE TITLE
django2.1 ImportError: cannot import name 'QUERY_TERMS'

### ISSUE THREAD

**Issue by EdwardNian** [django-tastypie/django-tastypie#1566] opened 2018-08-14 02:55 UTC
django-tastypie 0.14.1 resources.py 
from django.db.models.sql.constants import QUERY_TERMS

**Comment by georgedorn** [comment] 2018-08-14 03:00
Duplicate of #1561

**Closed by georgedorn** 2018-08-14 03:00 UTC

**Comment by AyazSaiyed** [comment] 2019-08-23 07:19
Just write **pip install django==2.0** !   

> Thats all Have fun !!
